"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /classic ".\2. Backup site" "." "MPFSImg.bin"
"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /classic /C18 ".\2. Backup site" "." "MPFSImg.c"
"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /classic /ASM30 ".\2. Backup site" "." "MPFSImg.s"
"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /mpfs2 ".\1. Active site" "." "MPFSImg2.bin"
"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /mpfs2 /C18 ".\1. Active site" "." "MPFSImg2.c"
"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /mpfs2 /ASM30 ".\1. Active site" "." "MPFSImg2.s"
